# This is the global config file.
# There are two rules. Any custom variables go into the params section of this page.
# Prebuild options may be at the corresponding level defined in the hugo build.


# Basic Options
baseurl = "https://thinkingtree.codefra.in/"
title = "The Thinking Tree"
theme = "ga-hugo-theme"

# For comments to be enabled on a page, you need to add your disqus short name here.
# Get disqus shortname here: https://disqus.com/
disqusShortname = "codefra"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-119166503-1"

# Number in RSS feed
rssLimit =10
# When enabled, creates URL of the form /filename.html instead of /filename/.
uglyURLs = false


# Summaries in lists
summaryLength = 70

# Pagination Options
paginate = 10
paginatePath = "page"


# Directories to change. Keep defaults unless you want to change something
themesDir = "themes"
archetypeDir = "archetypes"
contentDir ="content"
dataDir ="data"
publishDir = "public"
layoutDir ="layouts"




# Your copyright notice - appears in site footer.
# To display a copyright symbol, type `&copy;`.
copyright = "&copy; 2018 CodeFRA"


# Generate Robots.txt
enableRobotsTXT =true



# Get last modified date for content from Git?
enableGitInfo = false

# Language - use some form of english
languageCode = "en-us"

# For debugging while testing only
log=true
logFile ="public/log.txt"


# Enable verbose logging.
verbose =true
verboseLog =true

# SEO Stuff

# Some parameters for the internal theme use
[params]
    #for debug
    open_at_top = false
    # After finishing this section config, make sure to look at manifest.json in the static folder
    # Color theme. These colors are used from the data/fonts folder
    #   Choose from `default`, `ocean`, `forest`, `coffee`, `dark`, or `1950s`.
    color_theme = "default"

    # Font style.
    #   Choose from `default`, `classic`, or `playfair`.
    # Color theme. These colors are used from the data/fonts folder
    font = "classic"

    # Site Author details.
    site_author_name = "Rahul Madhavan"
    role = "Founder, CodeFRA"
    # SEO Section
    # When pages don't have description
    default_description = "-273.15K. So Cool."
    # FB admin site handler
    facebook_admin_handle = "rahul.maddy"

    # Tags for twitter cards for sharing
    twitter_site_handle = "@codeFRA"
    twitter_creator_handle = "@rahul_maddy"
    # The favicon will be used to render the icon in the browser. Save this in the *static/folder*. Please save as png format images of square size.
    favicon = "favicon.png"
    # The favicon will be used to render the icon in the browser. Save this in the *static/folder*. Please save as png format images of square size.
    apple_touch_icon = "favicon.png"
    # Diplay a logo in navigation bar rather than title (optional).
    #   To enable, place an image in `static/` and reference its filename below. To disable, set the value to "".
    logo = "thinking_tree2.jpg"

    # Organizations/Affiliations.
    #   Separate multiple entries with a comma, using the form: `[ {name="Org1", url=""}, {name="Org2", url=""} ]`.
    organizations = [ { name = "Atidiv, Cuemath", url = "" }, { name = "Barclays, Nomura, Lehman Brothers", url = "" }, { name = "IIM Ahmedabad, IIT Madras", url = "" } ]

    about_page_portrait = "portrait.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
    email = "rahul.maddy@gmail.com"

    address = "Koramangala, Bangalore"
    phone = "+91 89714 07799"
    skype = ""

    # In case you want to add custom css and custom js, place them in (i) /static/css/ folder and (ii) /static/js/ folders
    # Add the filenames in the following two arrays
    custom_css = []
    custom_js = []
    # Below will be the active menu items for the navbar (navigation menu) at the top of the page
    # Please only include the names as given in the menu.main section below
    navbar_active = ["Home","Book Reviews","Projects","Publications","Posts","Contact"]

    # You can set a map in the front page in the contact section.
    # To use Google Maps, set `map = 1` and enter your API key that can be obtained here:
    #   https://developers.google.com/maps/documentation/javascript/get-api-key
    # To use OpenStreetMap tiles, set `map = 2`.
    # To use OpenStreetMap on a high traffic site, set `map = 3` and enter your API key that can be obtained here:
    #   https://www.mapbox.com/studio/account/tokens
    # To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
    #
    # Map provider:
    #   0: No map
    #   1: Google Maps
    #   2: OpenStreetMap (Mapnik)
    #   3: OpenStreetMap (Mapbox)
    map = true
    map_api_key = "AIzaSyBVTxUD4jy-hOKRaOquYgxpslLv1oMffFg"
    latitude = "12.932376"
    longitude = "77.630389"
    zoom = 15

    # You can enable comments on a page by page basis
    enable_comments = false
    # Will load the appropriate module only if above two are present
    comment_count = true


    # Highlight.js global options, View this demo and choose: https://highlightjs.org/static/demo/
    # 1) Do you need code highlighting at global level?
    #     Example: highlight = true
    # 2) What languages do you typically use. That you need globally loaded?
    #     Example: highlight_languages = ["go", "lisp", "ocaml"]
    # 3) What is the style scheme? Choose one of the styles from those listed in the demo
    #     Example: highlight_style = "github-gist"

    #   For the list of supported languages and styles, see:
    #   https://cdnjs.com/libraries/highlight.js/
    #
    #   For more info on the highlighting options, see:
    #   https://sourcethemes.com/academic/post/writing-markdown-latex/#highlighting-options
    highlight = false
    highlight_languages = ["htmlbars","bash"]
    # highlight_languages = []
    highlight_style = "ocean"

    # All the subresources are delivered throught an subresource integrity module. This helps if CDN is compromised
    # details here: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
    # Do you want to disable it? (not recommended)
    disable_sri = false

    # The following go on the footer.
    show_back_to_top = false

    # Below we set attributes for the featured pages on the website front page
    [params.featured_pages]

    # Below include the sections like books, courses or people (page types) for which you want the featured sections on the front page
    # Choose the number of pages per section you want featured on the front page as num_featured
    # Choose how you want sorted: You can choose any parameter found in the content front matter. Prefix ".Params." before the required field name
    # Choose sort order from "asc" or "desc"
    # There are three layouts you can choose from 1) card 2) large card 3) scroller 4) list
    # 1) "cards" 2) "carousel" 3) "list"
    # 1) If you choose card you can choose from the following options
    [[params.featured_pages.sections]]
        name = "books"
        title = "Books"
        title_color = "#333"
        subtitle = "The latest and greatest books"
        subtitle_color = "#999"
        num_featured = 6
        sort_field = ".Params.title"
        sort_order = "asc"
        card_title_font_color = "#a22"
        card_description_font_color = "#468"
        layout = 1


    [[params.featured_pages.sections]]
        name = "publications"
        title = "Publications"
        title_color = "#333"
        subtitle = "The latest and greatest publications"
        subtitle_color = "#999"
        num_featured = 1
        sort_field = ".Params.title"
        sort_order = "asc"
        layout = 1

    [[params.featured_pages.sections]]
        name = "posts"
        title = "Posts"
        title_color = "#333"
        subtitle = "The latest and greatest posts"
        subtitle_color = "#999"
        num_featured = 4
        sort_field = ".Params.title"
        sort_order = "asc"
        layout = 1

    [[params.featured_pages.sections]]
        name = "thoughts"
        title = "Thoughts"
        title_color = "#333"
        subtitle = "My newest thoughts"
        subtitle_color = "#999"
        num_featured = 2
        sort_field = ".Params.title"
        sort_order = "asc"
        layout = 1


    # Below we set attributes for the sharer
    [params.sharer]
        # Global and page settings for sharer has to be true for it to be shown
        sharer_active = true
        # There are three ways in which sharers can be included in your site.
        #        1. Through a fixed button that when clicked rolls up to show sharing buttons (bottom right of screen)
        #        2. Through a fixed menu on the left. This is active on larger screens. On smaller screens, there would be a fixed menu at bottom of screen
        #        3. Through a list of icons just before the start of content on content pages

        # 1. Sharer Rollup button
        sharer_rollup_button_active = true
        sharer_button_color = "#0095eb"
        sharer_pullup_button_icon = "fa-share-alt"
        # 2. Fixed menu
        # Note that this changes with screen width. This can be checked by pressing ctrl+shift+i on chrome
        sharer_fixed_menu_active = true
        show_menu_on_scroll = true
        # If show_menu_on_scroll is true, how much to scroll
        scroll_amount_to_activate_sharer = 20


    # Below we set attributes for the popup
    [params.popup]
        # Below is the global popup switch. This has to be true for there to be any popups on the site.
        # TO activate in a given page, this global switch has to be set to true, and the popup_active has to be true in the
        # page front matter (in the content folder)
        popup_active = true
        # Should popup be shown once per session or persist across browser close? default is persist
        reload_popup_once_per_session = false


        # We will allow three types of popups, timed popup, popup on given amount of scroll and exit intent popup
        # There are three ways of activating a popup.
        #        1) There is a button on the bottom right which can always be clicked.
        #        2) There is a delay activation
        #        3) There is an exit intent activation
        #        4) There is a scroll amount activation
        # Of these the button activation is always on. The others can be set here.

        # 1. Show Button at bottom of screen
        popup_show_button_on_bottom_right = true
        popup_button_color = "#0095eb"
        pullup_button_icon = "fa-fire"
        pullup_button_icon_color = "#fff"



        # 2. Delay activation
        activate_popup_on_delay = true
        seconds_before_activation = 10

        # 3. Exit intent activation
        activate_popup_on_exit_intent = true
        # The sensitivity is triggered by how fast the user takes the mouse out from top of the window (measured as mouse y coordinate when exit event is triggered)
        exit_intent_sensitivity = 20

        # 4. Amount of scroll activation
        activate_popup_on_scroll = true
        scroll_percentage_before_activation = 0.6


        # The popup will have
        #    a) A title
        #    b) explanatory text
        #    c) an image on the right or as a full background
        #    d) A formspree form for collecting name and email id
        #    e) A subscribe now button

        # choose from a font-awesome icon for the popup pullup (where applicable)

        title = "Subscribe Now"
        title_color = "#aaaaaa"
        subtitle = "Curated selection of articles straight to your inbox"
        subtitle_color = "#ffaa11"
        # Use img_position = 1 for full image background and use img_position = 2 for image on the right
        img_position = 2
        img_source = "/img/flowers_line_drawing.png"

        # form
        form_label_color = "#ffaa33"

        # form submit text
        submit_text = "Subscribe"
        submit_text_color = "#ccaaaa"
        submit_button_color = "blue"

        # Tries to return to the referrer page, but in case that fails, the option below
        link_after_submit = "/subscriptionsuccess/"

        popup_submission_mail = "rahul.maddy@gmail.com"
        popup_submission_subject = "New subscription for your site!"
        secondary_forwarding_emails = ["rahul.maddy@gmail.com","ksm@ksmadhavan.in"]

        # Close popup by clicking outside the box
        close_on_click_outside = true
        # Close popup by pressing escape
        close_on_escape = true

        [[params.popup.form_inputs]]
            name="name"
            required="required"
            type="text"
            helper_text = "Your Name *"

        [[params.popup.form_inputs]]
            name = "Email ID"
            requried = "required"
            type= "email"
            helper_text = "Your Email *"










    [[params.footer_network]]
        url = "https://www.facebook.com/rahul.maddy"
        iconpack = "fa"
        icon = "fa-facebook"

    [[params.footer_network]]
        url = "https://www.linkedin.com/in/rahul-madhavan/"
        iconpack = "fa"
        icon = "fa-linkedin"

    [[params.footer_network]]
        url = "http://github.com/p10rahulm"
        iconpack = "fa"
        icon = "fa-github"

# Menus
[menu]
    [[menu.main]]
        name = "Home"
        url = "./#about"
        weight = 1


    [[menu.main]]
        name = "Posts"
        url = "./posts/"
        weight = 2

    [[menu.main]]
        name = "Book Reviews"
        url = "#projects"
        weight = 3

    [[menu.main]]
        name = "Publications"
        url = "./publication/"
        weight = 5

    [[menu.main]]
        name = "Projects"
        url = "./project/"
        weight = 4

    [[menu.main]]
        name = "Contact"
        url = "/contact"
        weight = 6

# Here we choose the taxonomies. Various types of pages use various taxonomies
[taxonomies]
    tag = "tags"
    category = "categories"
    project = "projects"
    division = "divisions"
    team = "teams"
    genre = "genres"
    subject = "subjects"
    review_category = "review_categories"
    publication_type = "publication_types"


# Configure the English version of the website.
# TODO: ADD OTHER LANGUAGE SUPPORT
[Languages.en]
  languageCode = "en-in"

[outputs]
    home = [ "HTML", "CSS", "RSS", "JSON"]
    section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/readfiles/bfconfig/
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).


# We are using the below shortcode for image processing in our documents
[imaging]
    # Default resample filter used for resizing. Default is Box,
    # a simple and fast averaging filter appropriate for downscaling.
    # See https://github.com/disintegration/imaging
    # and   https://gohugo.io/content-management/image-processing/
    resampleFilter = "box"

    # Defatult JPEG quality setting. Default is 75.
    quality = 75

    # Anchor used when cropping pictures.
    # Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
    # Smart Cropping is content aware and tries to find the best crop for each image.
    # Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
    anchor = "smart"

[outputFormats]
    [outputFormats.json]
        baseName = "manifest"
        isPlainText = true
    [outputFormats.css]
        baseName = "styles"
